apiVersion: batch/v1
kind: Job
metadata:
  namespace: example06
  generateName: smoke-tests-
  labels:
    codefresh.io/cert: smoke-job  
    annotations:
      argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: dummy-message
        image: alpine
        command:
          - "sleep"
          - "5"
      restartPolicy: Never
  backoffLimit: 2    
