---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  template:
    spec:
      containers:
      - name: webserver-simple
        image: docker pull ghcr.io/vishn9893/gitops-cert-level-2-examples:1.0
